version: "3.8"

networks:
  my_bridge_network:
    driver: bridge

services:
  frontend:
    build:
      context: ./front_hm2
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - my_bridge_network
    depends_on:
      - backend 

  backend:
    build:
      context: ./back_hm2
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081" 
    networks:
      - my_bridge_network
